# -*- coding: utf-8 -*-
"""scrape_nba_assists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hKAu4e7jzcDv-N1OlYuvdmvJuLqbHC5
"""

!pip -q install pandas requests beautifulsoup4 lxml networkx matplotlib python-docx

import pandas as pd, os, textwrap

csv_path = f"{BASE}/gsw10_games_links_2017_18.csv"

csv_text = """date,opp,home_away,final_score,espn_box,espn_game,nba_game,bbr_box
2017-10-17,HOU,vs,"GSW 121–122 HOU",https://www.espn.com/nba/boxscore/_/gameId/400974438,https://www.espn.com/nba/game/_/gameId/400974438/rockets-warriors,https://www.nba.com/game/hou-vs-gsw-0021700002,https://www.basketball-reference.com/boxscores/201710170GSW.html
2017-10-25,TOR,vs,"GSW 117–112 TOR",https://www.espn.com/nba/boxscore/_/gameId/400974814,https://www.espn.com/nba/game/_/gameId/400974814/raptors-warriors,https://www.nba.com/game/tor-vs-gsw-0021700063,https://www.basketball-reference.com/boxscores/201710250GSW.html
2017-11-02,SAS,@,"GSW 112–92 SAS",https://www.espn.com/nba/boxscore/_/gameId/400974868,https://www.espn.com/nba/game/_/gameId/400974868/warriors-spurs,https://www.nba.com/game/gsw-vs-sas-0021700104,https://www.basketball-reference.com/boxscores/201711020SAS.html
2017-11-16,BOS,@,"GSW 88–92 BOS",https://www.espn.com/nba/boxscore/_/gameId/400974966,https://www.espn.com/nba/game/_/gameId/400974966/warriors-celtics,https://www.nba.com/game/gsw-vs-bos-0021700181,https://www.basketball-reference.com/boxscores/201711160BOS.html
2017-12-25,CLE,vs,"GSW 99–92 CLE",https://www.espn.com/nba/boxscore/_/gameId/400974446,https://www.espn.com/nba/game/_/gameId/400974446/cavaliers-warriors,https://www.nba.com/game/cle-vs-gsw-0021700494,https://www.basketball-reference.com/boxscores/201712250GSW.html
2018-01-04,HOU,@,"GSW 124–114 HOU",https://www.espn.com/nba/boxscore/_/gameId/400975312,https://www.espn.com/nba/game/_/gameId/400975312/warriors-rockets,https://www.nba.com/game/gsw-vs-hou-0021700566,https://www.basketball-reference.com/boxscores/201801040HOU.html
2018-01-15,CLE,@,"GSW 118–108 CLE",https://www.espn.com/nba/boxscore/_/gameId/400975392,https://www.espn.com/nba/game/_/gameId/400975392/warriors-cavaliers,https://www.nba.com/game/gsw-vs-cle-0021700646,https://www.basketball-reference.com/boxscores/201801150CLE.html
2018-01-27,BOS,vs,"GSW 109–105 BOS",https://www.espn.com/nba/boxscore/_/gameId/400975474,https://www.espn.com/nba/game/_/gameId/400975474/celtics-warriors,https://www.nba.com/game/bos-vs-gsw-0021700739,https://www.basketball-reference.com/boxscores/201801270GSW.html
2018-02-10,SAS,vs,"GSW 122–105 SAS",https://www.espn.com/nba/boxscore/_/gameId/400975802,https://www.espn.com/nba/game/_/gameId/400975802/spurs-warriors,https://www.nba.com/game/sas-vs-gsw-0021700846,https://www.basketball-reference.com/boxscores/201802100GSW.html
2018-02-14,POR,@,"GSW 117–123 POR",https://www.espn.com/nba/boxscore/_/gameId/400975610,https://www.espn.com/nba/game/_/gameId/400975610/warriors-trail-blazers,https://www.nba.com/game/gsw-vs-por-0021700882,https://www.basketball-reference.com/boxscores/201802140POR.html
"""

open(csv_path, "w").write(textwrap.dedent(csv_text))
df_links = pd.read_csv(csv_path)
df_links

import re, time, requests, pandas as pd
from collections import Counter
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

links = pd.read_csv(csv_path)

# Roster GSW 2017–18 (adicione se aparecer alguém a mais)
GSW_PLAYERS = {
    "Stephen Curry","Klay Thompson","Kevin Durant","Draymond Green","Zaza Pachulia",
    "Andre Iguodala","Shaun Livingston","David West","JaVale McGee","Jordan Bell",
    "Kevon Looney","Omri Casspi","Nick Young","Patrick McCaw","Quinn Cook"
}
def last2(name):
    toks = str(name).split()
    return " ".join(toks[-2:]).lower()
GSW_LAST2 = { last2(n) for n in GSW_PLAYERS }

def make_session():
    s = requests.Session()
    retries = Retry(total=5, connect=5, read=5, backoff_factor=1.5,
                    status_forcelist=[429,500,502,503,504], allowed_methods=["GET"])
    s.mount("https://", HTTPAdapter(max_retries=retries))
    s.headers.update({"User-Agent":"Mozilla/5.0 (Colab academic scraper)"})
    return s
session = make_session()

def espn_event_id(espn_game_url: str) -> str:
    return str(espn_game_url).split("gameId/")[-1].split("/")[0]

def espn_summary_url(event_id: str) -> str:
    return f"https://site.api.espn.com/apis/site/v2/sports/basketball/nba/summary?event={event_id}"

RE_AST1 = re.compile(r"^(?P<finisher>.*?)\s+makes\s+.*?\((?P<assistant>.*?)\s+assists\)", re.IGNORECASE)
RE_AST2 = re.compile(r"^(?P<finisher>.*?)\s+makes\s+.*?\(assist\s+by\s+(?P<assistant>.*?)\)", re.IGNORECASE)

def extract_pairs_from_summary(summary_json: dict):
    pairs = []
    plays = summary_json.get("plays") or []
    for p in plays:
        txt = (p.get("text") or "").strip()
        if "assist" not in txt.lower():
            continue
        m = RE_AST1.search(txt) or RE_AST2.search(txt)
        if not m:
            continue
        finisher  = m.group("finisher").strip()
        assistant = m.group("assistant").strip()
        if last2(finisher) in GSW_LAST2:
            pairs.append((assistant, finisher))
    return pairs

all_rows = []
for _, row in links.iterrows():
    date, opp = row["date"], row["opp"]
    eid = espn_event_id(row["espn_game"])
    url = espn_summary_url(eid)
    try:
        r = session.get(url, timeout=60); r.raise_for_status()
        pairs = extract_pairs_from_summary(r.json())
        counts = Counter(pairs)
        out_rows = [[date, opp, "GSW", a, b, c] for (a,b), c in counts.items()]
        pd.DataFrame(out_rows, columns=["date","opponent","team","assistant","finisher","assists"])\
          .to_csv(f"{BASE}/pairs_{date}_{opp}.csv", index=False)
        print(f"[{date} {opp}] pares extraídos: {len(out_rows)}")
        all_rows.extend(out_rows)
        time.sleep(0.5)
    except Exception as e:
        print(f"[erro] {date} {opp}: {e}")

agg = pd.DataFrame(all_rows, columns=["date","opponent","team","assistant","finisher","assists"])
agg.to_csv(f"{BASE}/out_pairs_10games.csv", index=False)
summary = agg.groupby(["date","opponent"]).agg(
    total_assists=("assists","sum"),
    unique_pairs=("assists","count"),
    gsw_players=("finisher", lambda s: len(set(s)))
).reset_index()
summary.to_csv(f"{BASE}/summary_by_game.csv", index=False)

agg.head(), summary

import pandas as pd, numpy as np, matplotlib.pyplot as plt, networkx as nx

agg = pd.read_csv(f"{BASE}/out_pairs_10games.csv")

# Heatmap agregado A→B
mat = agg.pivot_table(index="assistant", columns="finisher", values="assists", aggfunc="sum", fill_value=0)
plt.figure(figsize=(8,6))
plt.imshow(mat.values, aspect="auto")
plt.xticks(range(len(mat.columns)), mat.columns, rotation=45, ha="right")
plt.yticks(range(len(mat.index)), mat.index)
plt.title("Aggregate A→B assistance heatmap (10 games)")
plt.colorbar(label="assists")
plt.tight_layout()
plt.savefig(f"{BASE}/agg_heatmap_10j.png", dpi=160)
plt.close()

# Grafo agregado
G = nx.DiGraph()
for _, r in agg.iterrows():
    u, v, w = r["assistant"], r["finisher"], int(r["assists"])
    if G.has_edge(u,v): G[u][v]["weight"] += w
    else: G.add_edge(u,v, weight=w)

pos = nx.spring_layout(G, seed=7)
widths = [0.5 + 0.6*d["weight"] for _,_,d in G.edges(data=True)]
plt.figure(figsize=(8,6))
nx.draw_networkx_nodes(G, pos, node_size=900)
nx.draw_networkx_labels(G, pos, font_size=8)
nx.draw_networkx_edges(G, pos, width=widths, arrows=True, arrowstyle="-|>", arrowsize=12)
plt.title("Aggregate pass (assistance) graph — width ∝ assists")
plt.tight_layout()
plt.savefig(f"{BASE}/agg_graph_10j.png", dpi=160)
plt.close()

f"{BASE}/agg_heatmap_10j.png", f"{BASE}/agg_graph_10j.png"

import pandas as pd, numpy as np, matplotlib.pyplot as plt, networkx as nx

def plot_game(date, opp, path_csv):
    df = pd.read_csv(path_csv)
    if df.empty:
        print(f"{date} {opp}: sem assistências parseadas.")
        return
    # Heatmap
    mat = df.pivot_table(index="assistant", columns="finisher", values="assists", fill_value=0)
    plt.figure(figsize=(6,4))
    plt.imshow(mat.values, aspect="auto")
    plt.xticks(range(len(mat.columns)), mat.columns, rotation=45, ha="right")
    plt.yticks(range(len(mat.index)), mat.index)
    plt.title(f"Heatmap A→B – {date} vs {opp}")
    plt.colorbar(label="assists")
    plt.tight_layout()
    plt.savefig(f"/content/heatmap_{date}_{opp}.png", dpi=160)
    plt.close()

    # Grafo
    G = nx.DiGraph()
    for _, r in df.iterrows():
        G.add_edge(r["assistant"], r["finisher"], weight=int(r["assists"]))
    pos = nx.spring_layout(G, seed=7)
    widths = [0.5 + 0.6*d["weight"] for _,_,d in G.edges(data=True)]
    plt.figure(figsize=(6,4))
    nx.draw_networkx_nodes(G, pos, node_size=800)
    nx.draw_networkx_labels(G, pos, font_size=8)
    nx.draw_networkx_edges(G, pos, width=widths, arrows=True, arrowstyle="-|>", arrowsize=12)
    plt.title(f"Grafo A→B – {date} vs {opp}")
    plt.tight_layout()
    plt.savefig(f"/content/graph_{date}_{opp}.png", dpi=160)
    plt.close()

# Gerar para todos
for _, row in links.iterrows():
    date, opp = row["date"], row["opp"]
    plot_game(date, opp, f"/content/pairs_{date}_{opp}.csv")
"ok"